defmodule Galixir.Generator.Header do
  @moduledoc """
  Generates the static header implementation for a Galixir algebra module.

  This generator injects compile-time metadata and helper functions into an
  algebra implementation module. The generated metadata describes the algebra
  structure, including its metric, basis blade layout, multiplication
  table, and coefficient storage information.

  The generated functions provide access to:

    * the number of stored coefficients
    * the algebra dimension
    * the metric
    * the precomputed geometric product table
    * the mapping between blade names and storage indices

  The implementation is generated from a `Galixir.Meta` structure and is shared
  by all concrete algebra modules generated by Galixir.

  The generated metadata is stored as module attributes to allow other generated
  operations to efficiently access compile-time constants without recomputing
  them.
  """

  alias Galixir.Meta
  alias Galixir.GeneratorBehaviour
  @behaviour GeneratorBehaviour

  @impl GeneratorBehaviour
  def generate_implementation(%Meta{
        metric: metric,
        table: table,
        blade_indices: blade_indices,
        blade_aliases: blade_aliases,
        bases: bases,
        epsilon: epsilon
      }) do
    blade_count = Galixir.Table.blade_count(metric)

    [
      quote do
        @metric unquote(Macro.escape(metric))
        @table unquote(Macro.escape(table))
        @blade_count unquote(blade_count)
        @basis_names unquote(Tuple.to_list(bases) |> Enum.map(&to_string/1))
        @blade_indices unquote(Macro.escape(blade_indices))
        @blade_aliases unquote(Macro.escape(blade_aliases))
        @epsilon unquote(epsilon)

        def epsilon() do
          @epsilon
        end

        @doc """
        Returns the number of coefficients stored by the algebra.

        A dimension `n` algebra contains `2^n` basis blades.
        """
        def blade_count() do
          @blade_count
        end

        @doc """
        Returns the dimension of the algebra.

        This is the number of basis vectors defined by the metric.
        """
        def dimension do
          tuple_size(@metric)
        end

        @doc """
        Returns the metric of the algebra.

        Example:

            {1, 1, 1, 0}

        represents a projective geometric algebra with three Euclidean basis
        vectors and one null basis vector.
        """
        def metric do
          @metric
        end

        @doc """
        Returns the multiplication table for the algebra.

        The table contains precomputed geometric products between basis blades.
        Each entry maps `{left_blade, right_blade}` to `{coefficient, result_blade}`.

        The blades are represented internally as bitmasks.

        ## Example

            iex> table() |> Map.has_key?({#{unquote(elem(bases, 0))}, #{unquote(elem(bases, 0))}})
            #{unquote(elem(metric, 0) != 0)}
        """
        def table do
          @table
        end

        @doc """
        Returns the mapping between blade names and storage indices.

        Blade coefficients are stored in a fixed-blade_count tuple. This map translates
        canonical blade names into their corresponding tuple index.

        ## Example

            iex> blade_indices()[:e#{unquote(elem(bases, 0))}]
            1
        """
        def blade_indices do
          @blade_indices
        end
      end
    ]
  end
end
