defmodule Galixir.Generator.Header do
  @moduledoc """
  Generates the static header implementation for a Galixir algebra module.

  This generator injects compile-time metadata and helper functions into an
  algebra implementation module. The generated metadata describes the algebra
  structure, including its metric signature, basis blade layout, multiplication
  table, and coefficient storage information.

  The generated functions provide access to:

    * the number of stored coefficients
    * the algebra dimension
    * the metric signature
    * the precomputed geometric product table
    * the mapping between blade names and storage indices

  The implementation is generated from a `Galixir.Meta` structure and is shared
  by all concrete algebra modules generated by Galixir.

  The generated metadata is stored as module attributes to allow other generated
  operations to efficiently access compile-time constants without recomputing
  them.
  """

  alias Galixir.Meta
  alias Galixir.GeneratorBehaviour
  @behaviour GeneratorBehaviour

  @impl GeneratorBehaviour
  def generate_implementation(%Meta{
        module: module,
        signature: signature,
        table: table,
        blade_indices: blade_indices,
        blade_aliases: blade_aliases,
        size: size,
        bases: bases
      }) do
    [
      quote do
        @signature unquote(Macro.escape(signature))
        @table unquote(Macro.escape(table))
        @size unquote(size)
        @blade_indices unquote(Macro.escape(blade_indices))
        @blade_aliases unquote(Macro.escape(blade_aliases))

        @doc """
        Returns the number of coefficients stored by the algebra.

        A dimension `n` algebra contains `2^n` basis blades.
        """
        def size() do
          @size
        end

        @doc """
        Returns the dimension of the algebra.

        This is the number of basis vectors defined by the signature.
        """
        def dimension do
          tuple_size(@signature)
        end

        @doc """
        Returns the metric signature of the algebra.

        Example:

            {1, 1, 1, 0}

        represents a projective geometric algebra with three Euclidean basis
        vectors and one null basis vector.
        """
        def signature do
          @signature
        end

        @doc """
        Returns the multiplication table for the algebra.

        The table contains precomputed geometric products between basis blades.
        Each entry maps `{left_blade, right_blade}` to `{coefficient, result_blade}`.

        The blades are represented internally as bitmasks.

        ## Example

            iex> #{unquote(module)}.table() |> Map.has_key?({#{unquote(elem(bases, 0))}, #{unquote(elem(bases, 0))}})
            #{unquote(elem(signature, 0) != 0)}
        """
        def table do
          @table
        end

        @doc """
        Returns the mapping between blade names and storage indices.

        Blade coefficients are stored in a fixed-size tuple. This map translates
        canonical blade names into their corresponding tuple index.

        ## Example

            iex> #{unquote(module)}.blade_indices()[:e#{unquote(elem(bases, 0))}]
            1
        """
        def blade_indices do
          @blade_indices
        end
      end
    ]
  end
end
